### ISSUE TITLE
Adding a structure to the top level of a structure

### ISSUE THREAD

**Issue by xpz25nfh** [particledecay/ansible-jsonpatch#12]
If I do this:

```
- name: "copying log file management data to '{{ docker_daemon_file }}'"
  json_patch:
    src: "{{ docker_daemon_file }}"
    operations:
      - op: add
        path: '/'
        value: "{{ docker_logging_options }}"
    pretty: true
    create: true
```

I'm expecting this:

```
        {
          "log-driver": "json-file",
          "log-opts": {
          "max-size": "50m",    
          "max-file": "1"    
                      }
        } 
```

But I'm getting this:

```
{
    "": {
        "log-driver": "json-file",
        "log_opts": {
            "max-size": "50m",
            "max-file": 1
        }
    }
}
```

How do I add a structure to the root node of a json structure?  I tried setting path to an empty string.

BTW, great module, thank you so much!

**Comment by particledecay** [comment]
I believe what's happening is `docker_logging_options` is probably a dict, which means you are adding a dict object to the root node... what you're probably hoping it'll do is (in Python) a `{}.update(docker_logging_options)` to *merge* the two objects. That's not what happens.

When you add, you're actually specifying the path to the object you're adding (or replacing, if it already exists). Try doing this instead:
```yaml
- name: "copying log file management data to '{{ docker_daemon_file }}'"
  json_patch:
    src: "{{ docker_daemon_file }}"
    operations:
      - op: add
        path: "/{{ item.key }}"
        value: "{{ item.value }}"
    pretty: true
    create: true
  with_items: "{{ docker_logging_options | dict2items }}"
```
