### ISSUE TITLE
exceptions.Exception does not take keyword arguments

### ISSUE THREAD

**Issue by delfer** [ParticleDecay/ansible-jsonpatch#2]
My playbook:
```
    - copy:
        content: ''
        dest: /etc/docker/daemon.json
        force: no
        group: docker
        owner: root
    - jsonpatch:
        src: /etc/docker/daemon.json
        operations:
          - op: add
            path: "/insecure-registries"
            value: "[]"
          - op: add
            path: "/insecure-registries/0"
            value: "reg:5000"
```

**Comment by garkin** [comment]
Created file is not a valid json. You need to fix `copy: { content: '{}' }`.
```yaml
- name: Create daemon.json file
  copy:
    content: '{}'
    dest: /etc/docker/daemon.json
    force: no
    
- name: Apply json changes
  json_patch: 
    src: "/etc/docker/daemon.json"
    operations:
    - op: add
      path: "/log-opts"
      value: 
        max-size: "10m"
        max-file: "3"
  register: JSON_RESULT

- name: Restart dockerd
  systemd:
    name: dockerd
    state: reloaded
  when: JSON_RESULT.changed
```
This is a common usage pattern, should be documented in the `readme.md` too.
