### ISSUE TITLE
How to add object with multiple values into array

### ISSUE THREAD

**Issue by OndrosI** [particledecay/ansible-jsonpatch#23]
Hello, i have this json

```json
{
  "repositories": [
    { 
      "name": "some-name", 
      "type": "vcs", 
      "url": "git@xxx.git" 
    }
  ]
}
```

and i am trying to create this

```json
{
  "repositories": [
    { 
      "name": "some-name", 
      "type": "vcs", 
      "url": "git@xxx.git" 
    },
    { 
      "name": "new-value", 
      "type": "vcs", 
      "url": "git@new-value.git" 
    }
  ]
}
```

but i dont know how. Is there possibility add multiple values into object?

like this:

```
- name: append key/values
  json_patch:
    src: /file.json
    operations:
      - op: add
        path: '/repositories/-'
        value: 
          name: "new-value"
          type: "vcs"
          url: "git@new-value.git"
    pretty: yes
    create: yes
```
