### ISSUE TITLE
pass type value is wrong

### ISSUE THREAD

**Issue by toanvan** [particledecay/ansible-jsonpatch#5]
I have file json
{
  "foo" : 1
},
 When I pass value using variable ansible, replace is wrong
 --
operations:
          - op: replace
            path: "/foo"
            value: "{{a}}"
Type of a variable is int a = 2 but output file json is
{
  "foo" : "2"
},
expected output is:
{
  "foo" : 2
},

**Comment by particledecay** [comment]
Sorry it's taken me this long to address... I just tried the following:

### test.yml
```yaml
- connection: local
  hosts: localhost
  gather_facts: false
  tasks:
    - name: set a value
      set_fact:
        json_test: 2
    - name: replace a value
      json_patch:
        src: "test.json"
        pretty: true
        operations:
          - op: replace
            path: "/foo/one"
            value: "{{ json_test }}"
```

### test.json
```json
{
    "foo": {
        "bar": "baz",
        "one": 1
    }
}
```

After running the test playbook, here is what `test.json` looks like:
```json
{
    "foo": {
        "bar": "baz",
        "one": 2
    }
}
```

However, once I change the `json_test` variable to `"2"` (explicitly a string) and run it again, this is what I get in `test.json`:
```json
{
    "foo": {
        "bar": "baz",
        "one": "2"
    }
}
```

So far I think this is expected behavior. Are you seeing something different?
