### ISSUE TITLE
Adding a new object to JSON Array

### ISSUE THREAD

**Issue by erfansahaf** [particledecay/ansible-jsonpatch#7]
Is there any option to push a new object to an array? something like this:

Existing array:
```
[
    {foo: bar},
    {bar: biz}
]
```

Desired array:
```
[
    {foo: bar},
    {bar: biz},
    {biz: foo},
]
```

**Note**: I don't know how many objects this array contains!

**Comment by erfansahaf** [comment]
I found out that it can be done using `End of array character (-)` but there is a problem.
Since it does not check if the object exists or not, this subject may end up with duplicate records.

Test JSON:
```
[
   "foo": "bar"
]
```

Patch:
```
- name: Add a member
  json_patch:
    src: "my.json"
    operations:
    - op: add
      path: "/-"
      value:
        foo: "bar"
```

Patched JSON:
```
[
   "foo": "bar",
   "foo": "bar"
]
```

**Comment by particledecay** [comment]
The `-` literally represents the end of the list, not the list itself, so the behavior suggests that you are targeting the end of the list and not the contents of the list. I have to assume the intention would be to append an item and not to only append if the item is unique and not already present in the list.

I'm thinking about how else you'd approach this situation, but in the meantime you can test for the member before adding it and use an ansible conditional to append only when necessary:

```yaml
- name: Check for member
  json_patch:
    src: "my.json"
    operations:
      - op: test
        path: /*/foo
        value: bar
    register: foo_exists

- name: Add a member
  json_patch:
    src: "my.json"
    operations:
      - op: add
        path: /-
        value:
          foo: bar
    when: not foo_exists.tested
```

I guess potentially there could be another option added for uniqueness checking? Like `unsafe_append` or something similar in intent.

**Comment by erfansahaf** [comment]
@particledecay Thanks for your response.

In my scenario, I'm trying to update a Prometheus config file that contains all exporters' addresses.
So in this case, I would test ***the whole object*** for the purpose of uniqueness, ***not just the key***.

How can I achieve this? Should I check every single key of the object?

**Comment by particledecay** [comment]
Sorry about the late response, @erfansahaf. I need to figure out a better way to get GitHub notifications.

Ok, so you'd have to test for existence in every single object in the array, yes. However, this module does provide that with the `*` notation. Using your previous example, I can test for the `{"biz": "foo"}` object in the array and register the result, then use that as a condition for appending a new object to the array:

```yaml
- name: Check for desired object in array
  json_patch:
    src: test.json
    operations:
      - op: test
        path: /*/biz
        value: foo
  register: appender
- name: Add new array item
  json_patch:
    src: test.json
    operations:
      - op: add
        path: /-
        value:
          biz: foo
  when: not appender.tested
```
